-- RIssue.nvim - Nvim integration for flamfrosticboio/rissue.lua
-- Copyright (C) 2026  flamfrosticboio
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

---@module "rissue"

--- Configuration used on rissue.nvim and rissue.lua
---@class rissue-nvim.Settings
--- Configuration for rissue.lua
---
--- This field is `nil` when user has not properly run setup for rissue.nvim
---@field core? rissue.Config
--- The remote name when getting url from context with:
--- ```bash
--- git remote get-url <remote_name>
--- ```
---
--- Default: "origin"
---
--- Can be overriden with environment variable: "REMOTE_NAME"
---
--- Example:
--- ```bash
--- # inside .env
--- REMOTE_NAME=base
--- ```
---@field remote_name string

---@class (partial) rissue-nvim.Opts: rissue-nvim.Settings
---@field core? rissue.Opts
