name: Lint
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    env:
      MISE_AUTO_INSTALL: false
    steps:
      - uses: actions/checkout@v6

      - name: Install Dependencies with mise
        uses: jdx/mise-action@v2
        with:
          install_args:
            aqua:Kampfkarren/selene

      - name: Run lint
        run: |
          mise run lint -- lua/

      - name: Run lint on tests
        run: |
          mise run lint_test -- test/
