name: Tests
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    env:
      ALL: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
      MISE_AUTO_INSTALL: false
    steps:
      - uses: actions/checkout@v6

      - name: Install Dependencies with mise
        uses: jdx/mise-action@v2
        with:
          install_args:
            neovim

      - name: Run tests
        run: |
          mise test
